### PR TITLE
Fix configuration file location display getting bold + hide cursor while running

### PR DESCRIPTION
**Pull request by ruby-R53**
Just some visual improvements to the interface. Because the last row of text ("Playing...") is bold, this parameter ends up applying to the first one too ("Config loaded from...") when another subtune is loaded, so I made it restore the console parameters when reaching that point to keep it the same.

And then I also made it hide the cursor while playing, just to make it look a bit cleaner :)

### CODE REVIEW

**Comment by drfiemost** [comment]
Nice touch hiding the cursor!

Anyway the filter curve messages are still in bold:
> **6581 filter range: 0.5
> 6581 filter curve: 0.5
> 8580 filter curve: 0.5**
> Config loaded from

Also please check the indentation, no tabs.

**Comment by ruby-R53** [comment]
> the filter curve messages are still in bold

that's weird, those don't appear here when ANSI is enabled

it clears the screen to make a new page *after* the player throws those messages

> Also please check the indentation, no tabs.

right, my bad

**Comment by drfiemost** [comment]
> it clears the screen to make a new page _after_ the player throws those messages
> 
Ah, you're right!

BTW, you've put the files in the wrong dir in your last commit.

**Comment by ruby-R53** [comment]
yeah, i deleted them and put on the right one after

**Comment by drfiemost** [comment]
I still see them :/
https://github.com/libsidplayfp/sidplayfp/pull/38/files

**Review by ruby-R53 — COMMENTED** [review]
here it is, didn't pay much attention when removing the wrong files lol

**Comment by drfiemost** [comment]
Something went wrong, indentation is not fixed

**Review by ruby-R53 — COMMENTED** [review]
there, i think the ones i deleted were the ones that had the correct identation, i apologize

**Comment by drfiemost** [comment]
Ok, thanks!

**Pull request merged**
